FROM mcr.microsoft.com/azure-sql-edge:latest

USER root

# https://docs.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.2#binary-archives
RUN curl -sSL -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-7.2.1-linux-arm64.tar.gz \
&& mkdir -p /opt/microsoft/powershell/7 \
&& tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7 \
&& chmod +x /opt/microsoft/powershell/7/pwsh \
&& ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-ver15
RUN pwsh -Command Install-Module -Name SqlServer -Force

# https://github.com/cagrin/sqlcmd-arm64
RUN mkdir -p /opt/mssql-tools/bin \
&& curl -sSL -o /opt/mssql-tools/bin/sqlcmd.c https://raw.githubusercontent.com/cagrin/sqlcmd-arm64/0.1.0/darwin/src/sqlcmd.c \
&& apt update && apt install -y gcc \
&& gcc /opt/mssql-tools/bin/sqlcmd.c -o /opt/mssql-tools/bin/sqlcmd